import {
  AutocompleteFunctionality,
  AutocompleteCustomization,
  ButtonFunctionality,
  ButtonCustomization,
  ButtonGroupFunctionality,
  ButtonGroupCustomization,
  CheckboxFunctionality,
  CheckboxCustomization,
  FabFunctionality,
  FabCustomization,
  FormComponentsFunctionality,
  FormComponentsCustomization,
  RadioFunctionality,
  RadioCustomization,
  RatingFunctionality,
  RatingCustomization,
  SelectFunctionality,
  SelectCustomization,
  SliderFunctionality,
  SliderCustomization,
  SwitchFunctionality,
  SwitchCustomization,
  TextfieldFunctionality,
  TextfieldCustomization,
  ToggleButtonFunctionality,
  ToggleButtonCustomization,
} from './components/inputs';
import {
  AvatarFunctionality,
  AvatarCustomization,
  BadgeFunctionality,
  BadgeCustomization,
  ChipFunctionality,
  ChipCustomization,
  DividerFunctionality,
  DividerCustomization,
  ListFunctionality,
  ListCustomization,
  MuiIconsFunctionality,
  MuiIconsCustomization,
  SvgIconFunctionality,
  SvgIconCustomization,
  TableFunctionality,
  TableCustomization,
  TooltipFunctionality,
  TooltipCustomization,
  TypographyFunctionality,
  TypographyCustomization,
} from './components/data_display';
import {
  AlertFunctionality,
  AlertCustomization,
  BackdropFunctionality,
  BackdropCustomization,
  DialogFunctionality,
  DialogCustomization,
  ProgressFunctionality,
  ProgressCustomization,
  SkeletonFunctionality,
  SkeletonCustomization,
  SnackbarFunctionality,
  SnackbarCustomization,
} from './components/feedback';
import {
  AccordionFunctionality,
  AccordionCustomization,
  AppBarFunctionality,
  AppBarCustomization,
  CardFunctionality,
  CardCustomization,
  PaperFunctionality,
  PaperCustomization,
} from './components/surfaces';
import {
  BottomNavigationFunctionality,
  BottomNavigationCustomization,
  BreadcrumbsFunctionality,
  BreadcrumbsCustomization,
  DrawerFunctionality,
  DrawerCustomization,
  LinkFunctionality,
  LinkCustomization,
  MenuFunctionality,
  MenuCustomization,
  PaginationFunctionality,
  PaginationCustomization,
  SpeedDialFunctionality,
  SpeedDialCustomization,
  StepperFunctionality,
  StepperCustomization,
  TabsFunctionality,
  TabsCustomization,
} from './components/navigation';
export default function App() {
  return (
    <>
      <h1>Welcome to Mastering MUI: Component Customization</h1>
      <TabsCustomization />
    </>
  );
}
